### ISSUE TITLE
Show partial of previous / next image

### ISSUE THREAD

**Issue by jaylaw81** [femioladeji/react-slideshow#124]
Enhancement request to add ability to see the next or previous image in the slide show and able to determine how much is shown.

**Comment by femioladeji** [comment]
Thanks for the suggestion @jaylaw81 . I'll look into this and see what can be done

**Comment by lucasvazq** [comment]
You can achieve this using the following styles
```css
.custom-slideshow {
  width: 40rem;
  margin-left: auto;
  margin-right: auto;
  overflow: hidden;
}
.custom-slideshow .react-slideshow-wrapper {
  width: 30rem;
  margin-left: auto;
  margin-right: auto;
  overflow: visible;
}
```

Just call your Slideshow component with `custom-slideshow` class

I have 4 slides with different background color

![2021-06-01_07-07-38](https://user-images.githubusercontent.com/38964964/120306289-16569780-c2a8-11eb-8b20-2078630532aa.png)
