### ISSUE TITLE
Zindex of the react slide show?

### ISSUE THREAD

**Issue by Pugsly99** [femioladeji/react-slideshow#137]
I have a custom border that I want the slides to sit behind and I have tried many different solutions and I can only ever get it to sit on top of the border. I can see this because the border has rounded edges and the slideshow its self is just a rectangle. 

Any solutions? 

Thank you

**Comment by femioladeji** [comment]
Hi, @Pugsly99 I'm guessing you're trying to achieve something like this [https://codesandbox.io/s/affectionate-resonance-jylqk](https://codesandbox.io/s/affectionate-resonance-jylqk).

You can add this to your css file.
```css
.react-slideshow-wrapper.slide {
  border: 10px solid blue;
  border-radius: 100px;
}
```

I'll work on adding a new `cssClass` prop that you can pass to the slide
