### ISSUE TITLE
Indicators 

### ISSUE THREAD

**Issue by danoshi** [femioladeji/react-slideshow#221]
Hi, it's me again. I saw the example of customizing the indicators, but I have a question: Is it possible to use your indicators while only changing the background of the dots? My app has a default black screen, so when I set the indicators to true, I can't see them, except when I customize them with numbers, for example.

Thanks in advance for your help!

**Comment by danoshi** [comment]
Furthermore, I have some images with varying heights. Is it possible to instruct the slide component not to reserve space for the tallest image but instead align the items each time a new slide is chosen? Currently, I have a single tall picture, and when I switch to the next, smaller picture, my thumbnails remain positioned lower on the page, resulting in a significant gap between them.

**Comment by femioladeji** [comment]
@danoshi for the indicator you can style it this way as it was done here https://codesandbox.io/s/smoosh-shape-qwdy4t?file=/src/styles.css:178-431
```css
.slide-container
  .react-slideshow-container
  + ul.indicators
  .each-slideshow-indicator:before {
  position: absolute;
  top: 0;
  left: 0;
  width: 7px;
  height: 7px;
  border-radius: 50%;
  content: "";
  background: #fff;
  text-align: center;
}
```
You can still use the custom indicator without necessarily putting a number there

For the different height request, we currently don't have support for that. We are still working on implementing that
